In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("data/Advertising.csv")

In [3]:
df.head()

      TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

----
----
----
## Cross Validation with cross_val_score

----

<img src="grid_search_cross_validation.png">

----

In [4]:
X=df.drop("sales",axis=1)

In [5]:
y=df["sales"]

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
np.random.seed(42)
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=101)

In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:
scaler=StandardScaler()

In [11]:
scaler.fit(X_train)

StandardScaler()

In [12]:
X_train=scaler.transform(X_train)

In [13]:
X_test=scaler.transform(X_test)

In [15]:
from sklearn.linear_model import Ridge

In [16]:
model=Ridge(alpha=100)

In [17]:
from sklearn.model_selection import cross_val_score

In [18]:
scores=cross_val_score(model,X_train,y_train,scoring='neg_mean_squared_error',cv=5)

In [19]:
scores

array([-6.82773615, -6.93824123, -8.87314549, -8.09875208, -8.11849919])

In [22]:
abs(scores.mean())

np.float64(7.7712748271872725)

In [23]:
model=Ridge(alpha=1)

In [24]:
scores=cross_val_score(model,X_train,y_train,scoring='neg_mean_squared_error',cv=5)

In [26]:
abs(scores.mean())

np.float64(2.772968978937122)

In [27]:
model.fit(X_train,y_train)

Ridge(alpha=1)

In [28]:
y_final_test_pred = model.predict(X_test)

In [29]:
from sklearn.metrics import mean_squared_error

In [31]:
mean_squared_error(y_test,y_final_test_pred)

3.8001825079875227

## Cross_validate

In [34]:
## CREATE X and y
X=df.drop('sales',axis=1)
y=df["sales"]
# TRAIN TEST SPLIT
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)
# SCALE DATA
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X_train)
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)

In [35]:
from sklearn.model_selection import cross_validate

model=Ridge(alpha=100)

In [37]:
scores=cross_validate(model,X_train,y_train,
                      scoring=['neg_mean_squared_error',
                              'neg_mean_absolute_error'],cv=10)

In [39]:
scores=pd.DataFrame(scores)

In [40]:
scores

,fit_time,score_time,test_neg_mean_squared_error,test_neg_mean_absolute_error
0,0.002807,0.002689,-4.721382,-1.722421
1,0.002146,0.001607,-8.131560,-2.099793
2,0.001744,0.001558,-5.430813,-1.882343
3,0.001477,0.001649,-6.612950,-2.065729
4,0.001622,0.001374,-9.128764,-2.492847
5,0.001464,0.001422,-6.554434,-2.158478
6,0.002465,0.001650,-2.893365,-1.444877
7,0.002154,0.001070,-12.058364,-2.818786
8,0.001205,0.001053,-12.818306,-2.419345
9,0.001554,0.001189,-2.587867,-1.234893

In [41]:
model=Ridge(alpha=1)

In [42]:
scores=cross_validate(model,X_train,y_train,
                      scoring=['neg_mean_squared_error',
                              'neg_mean_absolute_error'],cv=10)

In [43]:
scores=pd.DataFrame(scores)

In [44]:
scores

,fit_time,score_time,test_neg_mean_squared_error,test_neg_mean_absolute_error
0,0.002109,0.001626,-2.911867,-1.331710
1,0.001642,0.001567,-2.784154,-1.269023
2,0.001579,0.001535,-1.098295,-0.876497
3,0.001568,0.001680,-1.812891,-1.113152
4,0.002775,0.002121,-2.308968,-1.257662
5,0.002553,0.002097,-2.051892,-1.067477
6,0.002259,0.001263,-2.431973,-1.304290
7,0.001420,0.001119,-2.229323,-1.376223
8,0.001262,0.001868,-8.569988,-1.760545
9,0.001998,0.001432,-1.432624,-0.847836

In [45]:
model.fit(X_train,y_train)

Ridge(alpha=1)

In [46]:
y_final_pred=model.predict(X_test)

In [47]:
mean_squared_error(y_test,y_final_pred)

3.8001825079875227