In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df=pd.read_csv("data/Advertising.csv")

In [6]:
df.head()

      TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [10]:
#Create X and y
X=df.drop('sales',axis=1)
y=df["sales"]
#Train Test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)
#scale the Data
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X_train)
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)

In [13]:
from sklearn.linear_model import ElasticNet
# help(ElasticNet)

In [14]:
base_elastic_net_model =ElasticNet()

In [17]:
param_grid={'alpha':[0.1,1,5,10,50,100],
            'l1_ratio':[.1,.5,.7,.95,.99,1]}

In [19]:
from sklearn.model_selection import GridSearchCV

In [22]:
grid_model=GridSearchCV(estimator=base_elastic_net_model,
                        param_grid=param_grid,
                       scoring='neg_mean_squared_error',
                       cv=5,
                       verbose=2 )

In [23]:
grid_model.fit(X_train,y_train)

Fitting 5 folds for each of 36 candidates, totalling 180 fits
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.7; total time=   0.0s
[CV] END ...........................alpha=0.1, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=0.1, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=0.1, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=0.1, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=0.1, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=0.1, l1_ratio=0.99; total time=   0.0s
[CV] END ...........................alpha=0.1, l1_ratio=0.99; total time=   0.0s
[CV] END ...........................alpha=0.1, l1_ratio=0.99; total time=   0.0s
[CV] END ...........................alpha=0.1, l1_ratio=0.99; total time=   0.0s
[CV] END ...........................alpha=0.1, l1_ratio=0.99; total time=   0.0s
[CV] END ..............................alpha=0.1, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=0.1, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=0.1, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=0.1, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=0.1, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.7; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.7; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.7; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.7; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.95; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.95; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.95; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.95; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.95; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.99; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.99; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.99; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.99; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.99; total time=   0.0s
[CV] END ................................alpha=1, l1_ratio=1; total time=   0.0s
[CV] END ................................alpha=1, l1_ratio=1; total time=   0.0s
[CV] END ................................alpha=1, l1_ratio=1; total time=   0.0s
[CV] END ................................alpha=1, l1_ratio=1; total time=   0.0s
[CV] END ................................alpha=1, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.7; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.7; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.7; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.7; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=5, l1_ratio=0.95; total time=   0.0s
[CV] END .............................alpha=5, l1_ratio=0.95; total time=   0.0s
[CV] END .............................alpha=5, l1_ratio=0.95; total time=   0.0s
[CV] END .............................alpha=5, l1_ratio=0.95; total time=   0.0s
[CV] END .............................alpha=5, l1_ratio=0.95; total time=   0.0s
[CV] END .............................alpha=5, l1_ratio=0.99; total time=   0.0s
[CV] END .............................alpha=5, l1_ratio=0.99; total time=   0.0s
[CV] END .............................alpha=5, l1_ratio=0.99; total time=   0.0s
[CV] END .............................alpha=5, l1_ratio=0.99; total time=   0.0s
[CV] END .............................alpha=5, l1_ratio=0.99; total time=   0.0s
[CV] END ................................alpha=5, l1_ratio=1; total time=   0.0s
[CV] END ................................alpha=5, l1_ratio=1; total time=   0.0s
[CV] END ................................alpha=5, l1_ratio=1; total time=   0.0s
[CV] END ................................alpha=5, l1_ratio=1; total time=   0.0s
[CV] END ................................alpha=5, l1_ratio=1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.95; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.95; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.95; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.95; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.95; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.99; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.99; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.99; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.99; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.99; total time=   0.0s
[CV] END ...............................alpha=10, l1_ratio=1; total time=   0.0s
[CV] END ...............................alpha=10, l1_ratio=1; total time=   0.0s
[CV] END ...............................alpha=10, l1_ratio=1; total time=   0.0s
[CV] END ...............................alpha=10, l1_ratio=1; total time=   0.0s
[CV] END ...............................alpha=10, l1_ratio=1; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=50, l1_ratio=0.95; total time=   0.0s
[CV] END ............................alpha=50, l1_ratio=0.95; total time=   0.0s
[CV] END ............................alpha=50, l1_ratio=0.95; total time=   0.0s
[CV] END ............................alpha=50, l1_ratio=0.95; total time=   0.0s
[CV] END ............................alpha=50, l1_ratio=0.95; total time=   0.0s
[CV] END ............................alpha=50, l1_ratio=0.99; total time=   0.0s
[CV] END ............................alpha=50, l1_ratio=0.99; total time=   0.0s
[CV] END ............................alpha=50, l1_ratio=0.99; total time=   0.0s
[CV] END ............................alpha=50, l1_ratio=0.99; total time=   0.0s
[CV] END ............................alpha=50, l1_ratio=0.99; total time=   0.0s
[CV] END ...............................alpha=50, l1_ratio=1; total time=   0.0s
[CV] END ...............................alpha=50, l1_ratio=1; total time=   0.0s
[CV] END ...............................alpha=50, l1_ratio=1; total time=   0.0s
[CV] END ...............................alpha=50, l1_ratio=1; total time=   0.0s
[CV] END ...............................alpha=50, l1_ratio=1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.7; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.99; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.99; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.99; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.99; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.99; total time=   0.0s
[CV] END ..............................alpha=100, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=100, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=100, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=100, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=100, l1_ratio=1; total time=   0.0s

GridSearchCV(cv=5, estimator=ElasticNet(),
             param_grid={'alpha': [0.1, 1, 5, 10, 50, 100],
                         'l1_ratio': [0.1, 0.5, 0.7, 0.95, 0.99, 1]},
             scoring='neg_mean_squared_error', verbose=2)

In [24]:
grid_model.best_estimator_

ElasticNet(alpha=0.1, l1_ratio=1)

In [25]:
grid_model.best_params_

{'alpha': 0.1, 'l1_ratio': 1}

In [26]:
pd.DataFrame(grid_model.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_alpha,param_l1_ratio,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.006377,0.005478,0.002152,0.000629,0.1,0.10,"{'alpha': 0.1, 'l1_ratio': 0.1}",-5.729406,-3.078854,-2.246779,-2.935092,-3.899895,-3.578005,1.197229,6
1,0.002915,0.000919,0.001344,0.000082,0.1,0.50,"{'alpha': 0.1, 'l1_ratio': 0.5}",-5.451783,-3.019647,-2.162397,-2.897276,-3.651147,-3.436450,1.113131,5
2,0.002866,0.000262,0.001550,0.000157,0.1,0.70,"{'alpha': 0.1, 'l1_ratio': 0.7}",-5.318700,-3.001665,-2.130422,-2.887378,-3.533484,-3.374330,1.070440,4
3,0.002753,0.000032,0.001439,0.000046,0.1,0.95,"{'alpha': 0.1, 'l1_ratio': 0.95}",-5.159153,-2.992437,-2.101619,-2.917443,-3.395444,-3.313219,1.014076,3
4,0.002704,0.000112,0.001518,0.000106,0.1,0.99,"{'alpha': 0.1, 'l1_ratio': 0.99}",-5.134425,-2.992479,-2.098289,-2.926011,-3.374491,-3.305139,1.004896,2
5,0.002746,0.000263,0.001504,0.000261,0.1,1.00,"{'alpha': 0.1, 'l1_ratio': 1}",-5.128280,-2.992562,-2.097516,-2.928209,-3.369300,-3.303173,1.002604,1
6,0.002786,0.000106,0.001518,0.000104,1.0,0.10,"{'alpha': 1, 'l1_ratio': 0.1}",-12.618087,-9.050387,-8.150255,-5.833390,-9.853176,-9.101059,2.214472,12
7,0.003302,0.000470,0.001542,0.000145,1.0,0.50,"{'alpha': 1, 'l1_ratio': 0.5}",-11.144133,-7.503501,-6.934685,-4.836610,-7.999498,-7.683686,2.038320,11
8,0.003074,0.000125,0.001486,0.000111,1.0,0.70,"{'alpha': 1, 'l1_ratio': 0.7}",-10.151439,-6.600257,-6.068279,-4.323150,-6.751986,-6.779022,1.894325,10
9,0.003581,0.000480,0.001630,0.000184,1.0,0.95,"{'alpha': 1, 'l1_ratio': 0.95}",-8.558370,-5.290184,-4.736965,-3.726732,-5.426440,-5.547738,1.619776,9
10,0.002910,0.000428,0.001740,0.000473,1.0,0.99,"{'alpha': 1, 'l1_ratio': 0.99}",-8.259191,-5.060275,-4.497887,-3.641611,-5.187360,-5.329265,1.563095,8
11,0.002697,0.000127,0.001524,0.000156,1.0,1.00,"{'alpha': 1, 'l1_ratio': 1}",-8.182305,-5.002235,-4.437146,-3.621408,-5.126533,-5.273925,1.548240,7
12,0.002718,0.000112,0.001436,0.000049,5.0,0.10,"{'alpha': 5, 'l1_ratio': 0.1}",-25.190381,-20.705002,-20.054501,-13.154631,-20.139666,-19.848836,3.852386,13
13,0.002906,0.000210,0.001662,0.000322,5.0,0.50,"{'alpha': 5, 'l1_ratio': 0.5}",-29.100261,-24.222632,-23.998718,-15.131906,-23.044631,-23.099629,4.506988,14
14,0.002760,0.000057,0.001522,0.000042,5.0,0.70,"{'alpha': 5, 'l1_ratio': 0.7}",-31.411299,-26.856793,-26.145376,-16.858064,-25.580770,-25.370461,4.728774,16
15,0.002748,0.000068,0.001509,0.000062,5.0,0.95,"{'alpha': 5, 'l1_ratio': 0.95}",-32.274554,-27.598190,-27.169133,-18.136959,-26.465600,-26.328887,4.578089,17
16,0.002642,0.000062,0.001403,0.000038,5.0,0.99,"{'alpha': 5, 'l1_ratio': 0.99}",-32.274554,-27.598190,-27.169133,-18.136959,-26.465600,-26.328887,4.578089,17
17,0.003885,0.001001,0.001914,0.000470,5.0,1.00,"{'alpha': 5, 'l1_ratio': 1}",-32.274554,-27.598190,-27.169133,-18.136959,-26.465600,-26.328887,4.578089,17
18,0.003714,0.000305,0.001760,0.000371,10.0,0.10,"{'alpha': 10, 'l1_ratio': 0.1}",-28.963432,-24.324152,-23.899671,-15.692266,-23.395017,-23.254908,4.274563,15
19,0.003234,0.000216,0.001553,0.000150,10.0,0.50,"{'alpha': 10, 'l1_ratio': 0.5}",-32.274554,-27.598190,-27.169133,-18.136959,-26.465600,-26.328887,4.578089,17
20,0.003807,0.000813,0.002052,0.000647,10.0,0.70,"{'alpha': 10, 'l1_ratio': 0.7}",-32.274554,-27.598190,-27.169133,-18.136959,-26.465600,-26.328887,4.578089,17
21,0.003115,0.000129,0.001562,0.000088,10.0,0.95,"{'alpha': 10, 'l1_ratio': 0.95}",-32.274554,-27.598190,-27.169133,-18.136959,-26.465600,-26.328887,4.578089,17
22,0.002756,0.000140,0.001491,0.000203,10.0,0.99,"{'alpha': 10, 'l1_ratio': 0.99}",-32.274554,-27.598190,-27.169133,-18.136959,-26.465600,-26.328887,4.578089,17
23,0.002967,0.000354,0.001581,0.000287,10.0,1.00,"{'alpha': 10, 'l1_ratio': 1}",-32.274554,-27.598190,-27.169133,-18.136959,-26.465600,-26.328887,4.578089,17
24,0.002893,0.000138,0.001513,0.000049,50.0,0.10,"{'alpha': 50, 'l1_ratio': 0.1}",-32.274554,-27.598190,-27.169133,-18.136959,-26.465600,-26.328887,4.578089,17
25,0.003563,0.000554,0.001556,0.000151,50.0,0.50,"{'alpha': 50, 'l1_ratio': 0.5}",-32.274554,-27.598190,-27.169133,-18.136959,-26.465600,-26.328887,4.578089,17
26,0.004400,0.000360,0.001912,0.000376,50.0,0.70,"{'alpha': 50, 'l1_ratio': 0.7}",-32.274554,-27.598190,-27.169133,-18.136959,-26.465600,-26.328887,4.578089,17
27,0.002935,0.000169,0.001514,0.000105,50.0,0.95,"{'alpha': 50, 'l1_ratio': 0.95}",-32.274554,-27.598190,-27.169133,-18.136959,-26.465600,-26.328887,4.578089,17
28,0.003168,0.000611,0.001613,0.000234,50.0,0.99,"{'alpha': 50, 'l1_ratio': 0.99}",-32.274554,-27.598190,-27.169133,-18.136959,-26.465600,-26.328887,4.578089,17
29,0.002966,0.000401,0.001652,0.000282,50.0,1.00,"{'alpha': 50, 'l1_ratio': 1}",-32.274554,-27.598190,-27.169133,-18.136959,-26.465600,-26.328887,4.578089,17
30,0.002914,0.000111,0.001868,0.000423,100.0,0.10,"{'alpha': 100, 'l1_ratio': 0.1}",-32.274554,-27.598190,-27.169133,-18.136959,-26.465600,-26.328887,4.578089,17
31,0.002955,0.000232,0.001528,0.000106,100.0,0.50,"{'alpha': 100, 'l1_ratio': 0.5}",-32.274554,-27.598190,-27.169133,-18.136959,-26.465600,-26.328887,4.578089,17
32,0.002885,0.000257,0.001507,0.000039,100.0,0.70,"{'alpha': 100, 'l1_ratio': 0.7}",-32.274554,-27.598190,-27.169133,-18.136959,-26.465600,-26.328887,4.578089,17
33,0.003366,0.000435,0.001553,0.000113,100.0,0.95,"{'alpha': 100, 'l1_ratio': 0.95}",-32.274554,-27.598190,-27.169133,-18.136959,-26.465600,-26.328887,4.578089,17
34,0.003358,0.000510,0.001707,0.000389,100.0,0.99,"{'alpha': 100, 'l1_ratio': 0.99}",-32.274554,-27.598190,-27.169133,-18.136959,-26.465600,-26.328887,4.578089,17
35,0.003835,0.001069,0.001772,0.000314,100.0,1.00,"{'alpha': 100, 'l1_ratio': 1}",-32.274554,-27.598190,-27.169133,-18.136959,-26.465600,-26.328887,4.578089,17

In [27]:
y_pred =grid_model.predict(X_test)

In [28]:
from sklearn.metrics import mean_squared_error

In [29]:
mean_squared_error(y_test,y_pred)

2.168258740185374