In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
df=pd.read_csv("173 mushrooms.csv")

In [12]:
df.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g

In [16]:
X=df.drop("class",axis=1)
y=df["class"]

In [17]:
X=pd.get_dummies(X,dtype=int,drop_first=True)

In [18]:
X

,cap-shape_c,cap-shape_f,cap-shape_k,cap-shape_s,cap-shape_x,cap-surface_g,cap-surface_s,cap-surface_y,cap-color_c,cap-color_e,...,population_n,population_s,population_v,population_y,habitat_g,habitat_l,habitat_m,habitat_p,habitat_u,habitat_w
0,0,0,0,0,1,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
1,0,0,0,0,1,0,1,0,0,0,...,1,0,0,0,1,0,0,0,0,0
2,0,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,1,0,0,0
3,0,0,0,0,1,0,0,1,0,0,...,0,1,0,0,0,0,0,0,1,0
4,0,0,0,0,1,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,0,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
8120,0,0,0,0,1,0,1,0,0,0,...,0,0,1,0,0,1,0,0,0,0
8121,0,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
8122,0,0,1,0,0,0,0,1,0,0,...,0,0,1,0,0,1,0,0,0,0
8123,0,0,0,0,1,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.15,random_state=101)

In [31]:
from sklearn.ensemble import GradientBoostingClassifier

In [32]:
gboost_model=GradientBoostingClassifier()

In [23]:
gboost_model.fit(X_train,y_train)

GradientBoostingClassifier()

In [24]:
gboost_model.feature_importances_

array([2.91150176e-04, 1.06435713e-16, 0.00000000e+00, 0.00000000e+00,
       7.75177578e-17, 1.04902579e-03, 0.00000000e+00, 1.27734798e-06,
       0.00000000e+00, 0.00000000e+00, 4.29742709e-17, 0.00000000e+00,
       5.02600855e-17, 0.00000000e+00, 0.00000000e+00, 1.59091455e-08,
       2.42139009e-03, 5.53798965e-02, 6.24175887e-04, 1.02539488e-02,
       1.82499853e-02, 4.87342340e-05, 6.14744334e-01, 8.63939501e-03,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.25092906e-02,
       1.12726874e-02, 0.00000000e+00, 1.98839855e-16, 0.00000000e+00,
       1.28425061e-17, 0.00000000e+00, 0.00000000e+00, 1.17991062e-17,
       3.61913265e-16, 0.00000000e+00, 2.11794217e-17, 5.86323133e-18,
       4.95499827e-04, 5.38450045e-06, 1.36009198e-01, 0.00000000e+00,
       1.62912176e-02, 4.47043435e-04, 6.12113083e-06, 4.95063766e-06,
       1.83319493e-05, 0.00000000e+00, 5.09697103e-02, 1.41068922e-05,
       0.00000000e+00, 0.00000000e+00, 4.59787330e-06, 0.00000000e+00,
       0.00000000e+00, 8.99394366e-04, 0.00000000e+00, 3.24831376e-03,
       0.00000000e+00, 0.00000000e+00, 5.33104127e-05, 0.00000000e+00,
       0.00000000e+00, 5.62862863e-04, 3.02342639e-03, 0.00000000e+00,
       1.58309673e-06, 6.05737440e-05, 8.78103661e-05, 5.68870643e-04,
       8.43895349e-05, 1.76797782e-05, 0.00000000e+00, 8.87320864e-04,
       1.11144472e-02, 2.14348545e-04, 2.08833318e-04, 0.00000000e+00,
       3.04953583e-02, 4.10000880e-03, 2.55020334e-03, 0.00000000e+00,
       1.36965833e-03, 0.00000000e+00, 3.26099733e-08, 1.35496377e-05,
       6.76506700e-04, 0.00000000e+00, 0.00000000e+00, 1.09217939e-16,
       0.00000000e+00, 1.00485103e-05, 0.00000000e+00])

In [25]:
from sklearn.metrics import classification_report,ConfusionMatrixDisplay,confusion_matrix,accuracy_score

In [26]:
pred=gboost_model.predict(X_test)

In [27]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           e       1.00      1.00      1.00       655
           p       1.00      1.00      1.00       564

    accuracy                           1.00      1219
   macro avg       1.00      1.00      1.00      1219
weighted avg       1.00      1.00      1.00      1219

In [28]:
from sklearn.model_selection import GridSearchCV

In [29]:
param_grid={
    "n_estimators":[50,100],
    "learning_rate":[0.1,0.05,0.2],
    "max_depth":[3,4,5,6]
}

In [30]:
grid_model=GridSearchCV(gboost_model,param_grid)

In [33]:
grid_model.fit(X_train,y_train)

GridSearchCV(estimator=GradientBoostingClassifier(),
             param_grid={'learning_rate': [0.1, 0.05, 0.2],
                         'max_depth': [3, 4, 5, 6], 'n_estimators': [50, 100]})

In [34]:
grid_model.best_params_

{'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 100}

In [35]:
pred =grid_model.predict(X_test)

In [36]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           e       1.00      1.00      1.00       655
           p       1.00      1.00      1.00       564

    accuracy                           1.00      1219
   macro avg       1.00      1.00      1.00      1219
weighted avg       1.00      1.00      1.00      1219